
#dataset:
 # train_images: "COMP9517/agropest12_projec/archive/train/images"
  #train_labels: "COMP9517/agropest12_projec/archive/train/labels"   # yolo txt per image
  #val_images:   "COMP9517/agropest12_projec/archive/val/images"
  #val_labels:   "COMP9517/agropest12_projec/archive/val/labels"
  #test_images:  "COMP9517/agropest12_projec/archive/test/images"
  #test_labels:  "COMP9517/agropest12_projec/archive/test/labels"
  #classes: 12
dataset:
  train_images: /workspace/COMP9517/agropest12_project/archive/train/images
  train_labels: /workspace/COMP9517/agropest12_project/archive/train/labels
  val_images:   /workspace/COMP9517/agropest12_project/archive/val/images
  val_labels:   /workspace/COMP9517/agropest12_project/archive/val/labels
  test_images: /workspace/COMP9517/agropest12_projec/archive/test/images
  test_labels: /workspace/COMP9517/agropest12_projec/archive/test/labels
  classes: 12
training:
  seed: 42
  # detection
  det:
    epochs: 20
    batch_size: 2
    lr: 1e-4
    weight_decay: 1e-4
  # classification
  cls:
    epochs: 5
    batch_size: 32
    lr: 1e-4
    weight_decay: 1e-4

model:
  detector: "rtdetr"       # rtdetr | retinanet
  classifier: "vit_b16"
  num_queries: 100

output:
  save_dir: "checkpoints"
  log_dir: "logs"
